platform :ios, '10.0'
install! 'cocoapods',
disable_input_output_paths: true,
generate_multiple_pod_projects: true

use_frameworks!

target 'UIIndexBar_Example' do
  pod 'UIIndexBar', :path => '../'

end
